label_messages = {
            "Adult": "Ah, exploring life's spicy corners, aren't we?",
            "Art & Design": "You're painting reality one brilliant idea at a time!",
            "Software Dev.": "Clearly, you speak fluent Python and dream in JavaScript.",
            "Crime & Law": "Sherlock would be proud of your detective instincts!",
            "Education & Jobs": "Always chasing knowledge—professors envy your enthusiasm.",
            "Hardware": "Your idea of fun involves wires, chips, and just a hint of solder smoke.",
            "Entertainment": "Hollywood could use someone with your impeccable taste.",
            "Social Life": "Your notifications must rival Times Square at night!",
            "Fashion & Beauty": "Even your pajamas could walk a runway.",
            "Finance & Business": "Wall Street should watch out for your savvy moves!",
            "Food & Dining": "Clearly, you believe life is too short for bland meals.",
            "Games": "Leveling up is basically your cardio.",
            "Health": "Avocados and yoga mats fear your unwavering dedication.",
            "History": "You've probably corrected a historian once or twice.",
            "Home & Hobbies": "You're turning DIY into an Olympic sport.",
            "Industrial": "Factories run smoother when you're in charge!",
            "Literature": "Shakespeare has nothing on your plot twists.",
            "Politics": "You're the master of diplomatic tweets and heated debates.",
            "Religion": "Your search for meaning deserves its own philosophy textbook.",
            "Science & Tech.": "You probably whisper \"Eureka!\" in your sleep.",
            "Software": "Debugging code is your favorite adrenaline sport.",
            "Sports & Fitness": "Even your sweat has a competitive streak.",
            "Transportation": "Your mind travels faster than a Tesla on autopilot.",
            "Travel": "Your passport stamps could fill a novel!"
        }